name: Fetch Key Provider

on:
  push: {}  # Trigger the workflow on every push event

jobs:
  fetch-keyprovider:
    runs-on: ubuntu-latest  # Workflow runs on Ubuntu virtual machines

    steps:
      - uses: actions/checkout@v3  # Checkout the current repository

      - name: Checkout private repository (access key logic)
        uses: actions/checkout@v3  # Checkout the private repository (requires PAT)
        with:
          repository: https://github.com/Eduardodcsm/private  # Replace with your details (full URL)
          ref: main  # Specific branch or tag (optional)
          token: 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  # PAT with access to private repo

      - name: Upload keyProvider.js as artifact
        uses: actions/upload-artifact@v2  # Upload fetched file as artifact
        with:
          name: keyProvider.js
          path: keyProvider.js  # Adjust path if needed
